# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Deed.create(category: 'suggested', deed_type: 'service', title: 'Lunch', description: 'Buy and share lunch with someone; a friend, a family member, or a stranger.', picture: '/category_hunger.png', user_id: 1)
Deed.create(category: 'suggested', deed_type: 'donation', title: 'Fundraiser', description: 'Donate to a local fundraiser.  Any amount helps.', picture: '/category_money.png', user_id: 1)
Deed.create(category: 'suggested', deed_type: 'service', title: 'Fundraiser', description: 'Donate your time to a local fundraiser. Even a short amount of time can do wonders.', picture: '/category_money.png', user_id: 1)
Deed.create(category: 'suggested', deed_type: 'donation', title: 'Food Drive', description: 'Help someone less fortunate eat.', picture: '/category_hunger.png', user_id: 2)
Deed.create(category: 'suggested', deed_type: 'service', title: 'Homework', description: 'Help a child with their homework. Give the gift of knowledge.', picture: '/category_children.png', user_id: 2)
Deed.create(category: 'suggested', deed_type: 'service', title: 'Compliment a Service Worker', description: 'The service industry is tough. We are always quick to comment on bad service. How about complimenting good service?', picture: '/category_community.png', user_id: 3)
Deed.create(category: 'suggested', deed_type: 'service', title: 'Toilet Paper', description: 'Be kind. Change that empty toilet paper roll.', picture: '/category_community.png', user_id: 3)
Deed.create(category: 'suggested', deed_type: 'donation', title: 'Feed the Meter', description: "Throw some change into a random person's meter. Parking tickets are expensive!", picture: '/category_community.png', user_id: 3)
Deed.create(category: 'suggested', deed_type: 'service', title: 'Lend your ear', description: 'Seek out someone who is struggling, and give them your undivided attention. A little listening can go a long way.', picture: '/category_community.png', user_id: 3)
Deed.create(category: 'suggested', deed_type: 'donation', title: 'Gifts Ahoy!', description: 'Spontaneously give a random gift to someone, anyone.', picture: '/category_money.png', user_id: 1)
Deed.create(category: 'suggested', deed_type: 'service', title: 'Trash It!', description: 'Pick up a piece of trash. A clean world is a better world.', picture: '/category_environment.png', user_id: 1)
Deed.create(category: 'suggested', deed_type: 'donation', title: 'Line Hop', description: 'Let someone go ahead of you in line. Simple, but people will always appreciate it.', picture: '/category_community.png', user_id: 1)
Deed.create(category: 'suggested', deed_type: 'donation', title: 'Tickets', description: 'Have extra tickets you arent using? Give them to someone!', picture: '/category_money.png', user_id: 2)
Deed.create(category: 'suggested', deed_type: 'service', title: 'Local Hospital', description: 'Commit to volunteering at your local hospital. This is a bigger commitment, but well worth it.', picture: '/category_health.png', user_id: 2)
Deed.create(category: 'suggested', deed_type: 'donation', title: 'School Goodies', description: 'Schools are often under-funded and in need. Donate some supplies.', picture: '/category_children.png', user_id: 2)
Deed.create(category: 'suggested', deed_type: 'donation', title: 'School Goodies', description: 'Schools are often under-funded and in need. Donate some equipment.', picture: '/category_children.png', user_id: 2)
Deed.create(category: 'suggested', deed_type: 'service', title: "School's In!", description: 'Schools are often under-funded and in need. Donate your time.', picture: '/category_children.png', user_id: 2)
Deed.create(category: 'suggested', deed_type: 'donation', title: 'Give a Book',  description: 'Read an awesome book? Pass it on to a friend', picture: '/category_community.png', user_id: 1)
Deed.create(category: 'suggested', deed_type: 'donation', title: 'Money Money Money',  description: 'Cash burning a hole in your pocket? Give it to me! No, seriously though, share some with someone who can use it.', picture: '/category_money.png', user_id: 3)
Deed.create(category: 'suggested', deed_type: 'donation', title: 'Encourage Sharing',  description: 'Encourage your kid to use their allowance to give a gift to someone else.', picture: '/category_children.png', user_id: 3)
Deed.create(category: 'suggested', deed_type: 'donation', title: "Other's Behalf",  description: "Donate to a cause on someone else's behalf", picture: '/category_money.png', user_id: 1)
Deed.create(category: 'suggested', deed_type: 'donation', title: "Give Blood",  description: "You have enough...", picture: '/category_health.png', user_id: 1)
Deed.create(category: 'suggested', deed_type: 'service', title: "Big Brother",  description: "Join a Big Brother program.", picture: '/category_children.png', user_id: 3)
Deed.create(category: 'suggested', deed_type: 'service', title: "Big Sister",  description: "Join a Big Sister program.", picture: '/category_children.png', user_id: 3)
Deed.create(category: 'suggested', deed_type: 'service', title: "Chauffeur",  description: "Offer to give someone a ride.", picture: '/category_community.png', user_id: 3)
Deed.create(category: 'suggested', deed_type: 'service', title: "Stand Up!",  description: "See someone being wronged? It's not hard to find. Do something! Say something!", picture: '/category_humanrights.png', user_id: 3)
Deed.create(category: 'suggested', deed_type: 'service', title: "Errands",  description: "Run an errand for someone. Come on, who wouldn't like that done for themselves?", picture: '/category_community.png', user_id: 2)
Deed.create(category: 'suggested', deed_type: 'service', title: "Cleaning service",  description: "Offer to clean someone's house or car.", picture: '/category_community.png', user_id: 2)
Deed.create(category: 'suggested', deed_type: 'service', title: "Friend Me",  description: "Befriend the new kid on the block, or that shy person who is just dying for someone to notice them. There's lots of wonderful people falling under the radar out there.", picture: '/category_community.png', user_id: 3)
Deed.create(category: 'suggested', deed_type: 'service', title: "Collections",  description: "Start a collection point. People are more likely to recycle if it's convenient for them!", picture: '/category_environment.png', user_id: 3)
Deed.create(category: 'suggested', deed_type: 'service', title: "Adopt a Cat",  description: "This will in all likelyhood be a gift to yourself in the long run.", picture: '/category_animals.png', user_id: 1)
Deed.create(category: 'suggested', deed_type: 'service', title: "Adopt a Dog",  description: "This will in all likelyhood be a gift to yourself in the long run.", picture:'/category_animals.png', user_id: 1)
Deed.create(category: 'suggested', deed_type: 'service', title: "Disabled friendly",  description: "Make your business disabled friendly. Or help/encourage others to do so.", picture:'/category_disabled.png', user_id: 3)
Deed.create(category: 'suggested', deed_type: 'service', title: "Scoop da Poop",  description: "We all know that EVERY dog owner scoop's their dog's poop. Yet, inevitably we manage to dodge some magically appearing piles throughout the week. Be a dear, clean it up.", picture: '/category_animals.png', user_id: 1)
Deed.create(category: 'suggested', deed_type: 'donation', title: "Give a Pet",  description: "Give a kid a pet. They will love you. Their parents probably wont.", picture: '/category_animals.png', user_id: 1)
Deed.create(category: 'suggested', deed_type: 'service', title: "Cookies",  description: "Who doesnt love fresh baked cookies? Bake some for your friends and family. Or even some strangers. Don't stop there either. Brownies and cupcakes are equally loved.", picture: '/category_community.png', user_id: 1)
Deed.create(category: 'suggested', deed_type: 'service', title: "Love the Rents",  description: "Seriously, this should be a no-brainer. But if you need a push... Tell the parents you love them already", picture: '/category_community.png', user_id: 2)
Deed.create(category: 'suggested', deed_type: 'service', title: "Soup Kitchen",  description: "Volunteer at your local soup kitchen", picture: '/category_homeless.png', user_id: 2)
Deed.create(category: 'suggested', deed_type: 'donation', title: "Homeless Hotel",  description: "Rent a hotel room for a homeless person. A place to stay for the night and a shower could be just what they need.", picture: '/category_homeless.png', user_id: 2)
Deed.create(category: 'suggested', deed_type: 'service', title: "Job Help",  description: "Help a homeless person find a job. This helps everyone. Heck, help me find a job.", picture: '/category_community.png', user_id: 2)
Deed.create(category: 'suggested', deed_type: 'service', title: "Disabled",  description: "Help a someone who is disabled. Be sure to ask them if they want to help first, please.", picture:'/category_disabled.png', user_id: 2)
Deed.create(category: 'local', deed_type: 'service', title: "Peninsula Humane Society",  description: "PHS/SPCA, a private non-profit guided by the humane ethic, builds healthy relationships between people and animals.", picture: 'http://www.peninsulahumanesociety.org/images/newlogo.gif', location: 'bay area', phone: '(555) 555-5555',  email: 'peninsulahumanesociety@gmail.com‎', url: 'www.peninsulahumanesociety.org/‎', user_id: 2)
